
// Extend the Package interface to include generatedMocks
export interface ExtendedPackage {
  id: string;
  name: string;
  description: string;
  interviews: number;
  generatedPrice: number;
  tutorPrice: number;
  // New Optional Field
  blackFridayPrice?: number; 
  originalPrice?: number;
  originalGeneratedPrice?: number;
  popular?: boolean;
  features: string[];
  generatedMocks?: {
    description: string;
    features: string[];
    benefits: string[];
  };
}

export interface UCATPackage {
  id: string;
  name: string;
  description: string;
  price: number;
  popular?: boolean;
  features: string[];
  baseFeatures?: string[];
  advancedFeatures?: string[];
  color: string;
  buttonColor: string;
}

export const interviewPackages: ExtendedPackage[] = [
  {
    id: 'essentials',
    name: 'Tailored Mock Interview – Essentials',
    description: 'Perfect for individual interview practice',
    interviews: 1,
    generatedPrice: 10,
    // blackFridayPrice: 40,
    tutorPrice: 45,
    features: [
      'A mock interview with Prometheus-powered university-specific questions',
      'Ensuring that your mock interview is as realistic as possible',
      'All of our tutors are current medical students',
    ],
    generatedMocks: {
      description: 'AI-powered university-specific mock questions',
      features: [
        '1 complete university-specific mock interview sets generated by Prometheus',
        'Includes model answers for self-assessment',
        'Up to date questions relevant for 2025/26 interviews',
      ],
      benefits: [
        'Practice at your own pace',
        'Review answers against model responses',
        'Instant access - no waiting for tutor availability',
        'Cost-effective practice option'
      ]
    }
  },
  {
    id: 'core',
    name: 'Core Interview Preparation',
    description: 'Comprehensive interview training',
    interviews: 3,
    generatedPrice: 15,
    // originalGeneratedPrice: 14,
    // blackFridayPrice: 115,
    tutorPrice: 125,
    originalPrice: 150,
    popular: true,
    features: [
      '3 mock interviews with Prometheus-powered university-specific mock questions',
      'Mock interviews tailored to the universities you are applying to',
      'Coverage of ethical scenarios, common trick questions, and general interview technique',
      'We will aim to match you with a tutor who has sat the interview you are sitting'
    ],
    generatedMocks: {
      description: 'Complete AI-powered interview preparation package',
      features: [
        '3 complete university-specific mock interview sets generated by Prometheus',
        'Includes model answers for self-assessment',
        'Interview questions from all common interview formats (MMI, panel, traditional)',
        'Up to date questions relevant for 2025/26 interviews',
      ],
      benefits: [
        'Comprehensive preparation at a fraction of tutor cost',
        'Instant delivery to your email',
        'Practice answering questions from multiple universities',
        'Structured preparation with clear progression',
        'Ideal for building confidence through repetition'
      ]
    }
  },
  {
    id: 'premium',
    name: 'Premium Interview Intensive',
    description: 'The Ultimate Interview Preparation',
    interviews: 4,
    generatedPrice: 20,
    // originalGeneratedPrice: 21,
    // blackFridayPrice: 200,
    tutorPrice: 250,
    originalPrice: 275,
    features: [
      '4 mock interviews with Prometheus-powered university-specific mock questions',
      'A Background knowledge session for success at the interview',
      'Mock interviews tailored to the universities you are applying to',
      'Coverage of ethical scenarios, common trick questions, and general interview technique',
      'Access to 24/7 business phone for medicine related questions'
    ],
    generatedMocks: {
      description: 'Ultimate AI-powered interview preparation system',
      features: [
        '4 complete university-specific mock interview sets generated by Prometheus',
        'Includes model answers for self-assessment',
        'Comprehensive MMI station preparation',
        'Up to date questions relevant for 2025/26 interviews',
        'Ideal for quick learners needing specific university practice',
      ],
      benefits: [
        'Most extensive question coverage available',
        'Tailored to match your personal application profile',
        'Advanced ethical scenario discussion guides',
        'Preparation for challenging or unexpected questions',
        'Ideal for serious applicants targeting competitive programs'
      ]
    }
  }
];

export const ucatPackages: UCATPackage[] = [
  {
    id: 'ucat_kickstart',
    name: 'Kickstart',
    description: 'For students building a solid UCAT foundation.',
    price: 200,
    color: 'bg-blue-500',
    buttonColor: 'bg-blue-600 hover:bg-blue-700',
    features: [
      '4 hours of core teaching across all UCAT sections',
      '£95 Unlimited question submissions to tutors + tutor phone access',
      'Performance tracking for every question you complete',
      'FREE Personalised weekly revision plan (£30 value)',
      'After four sessions, all students so far have seen a 15%+ score increase across all areas',
      'Data-led support on weak areas from day one'
    ]
  },
  {
    id: 'ucat_advance',
    name: 'Advance',
    description: 'For students who want targeted improvement.',
    price: 375,
    color: 'bg-purple-600',
    buttonColor: 'bg-purple-600 hover:bg-purple-700',
    baseFeatures: [
      '4 hours of core teaching',
      'Performance tracking on every question',
      'FREE Personalised weekly revision plan (£30 value)',
    ],
    advancedFeatures: [
      '+4 hours of targeted, question-specific refinement sessions',
      'Deep dives into the exact areas your data shows are weakest',
      'Focused drills to turn weaknesses into strengths',
      '£95 Unlimited question submissions to tutors + tutor phone access'
    ],
    features: [
      '8 hours of core teaching',
      '£95 Unlimited question submissions to tutors + tutor phone access',
      'Performance tracking on every question',
      'FREE Personalised weekly revision plan (£30 value)',
      '15%+ score increase guarantee',
      '4 hours of targeted, question-specific refinement sessions',
      'Deep dives into the exact areas your data shows are weakest',
      'Focused drills to turn weaknesses into strengths'
    ]
  },
  {
    id: 'ucat_mastery',
    name: 'Mastery',
    description: 'For students aiming for top-10% scores.',
    price: 575,
    popular: true,
    color: 'bg-indigo-600',
    buttonColor: 'bg-indigo-600 hover:bg-indigo-700',
    baseFeatures: [
      '4 hours of core teaching',
      'Performance tracking on every question',
      'FREE Personalised weekly revision plan (£30 value)',
      '4 hours of targeted refinement sessions',
      'Deep-dive weakness analysis',
      'Smart drills and focused practice'
    ],
    advancedFeatures: [
      '+4 hours of high-intensity, data-led refinement sessions',
      'Double the time, double the refinement for peak performance',
      'Built to get you test-day ready with total confidence',
      'Priority support and accelerated response times',
      'Advanced test-taking strategies for top percentile scores',
      'FREE Four conference tickets (£50 value)',
      '£95 Unlimited question submissions to tutors + tutor phone access'
    ],
    features: [
      '12 hours of comprehensive teaching',
      'Four conference tickets included (£50 value)',
      '£95 Unlimited question submissions to tutors + tutor phone access',
      'Performance tracking on every question',
      'FREE Personalised weekly revision plan (£30 value)',
      'Deep-dive weakness analysis',
      'Smart drills and focused practice',
      'High-intensity refinement for peak performance',
      'Built to get you test-day ready with total confidence',
      'Priority support and accelerated response times',
      'Advanced test-taking strategies for top percentile scores'
    ]
  },
  {
    id: 'ucat_elite',
    name: 'Elite',
    description: 'For students committed to exceptional results.',
    price: 800,
    color: 'bg-gray-900',
    buttonColor: 'bg-gray-900 hover:bg-gray-800',
    baseFeatures: [
      'Complete core teaching foundation',
      'Performance tracking on every question',
      'FREE Personalised weekly revision plan (£30 value)',
      'Targeted refinement sessions',
      'Deep-dive weakness analysis',
      'Smart drills and focused practice'
    ],
    advancedFeatures: [
      '20 hours comprehensive intensive teaching',
      'Maximum contact time for mastery',
      'Extended practice with expert feedback',
      'FREE Four conference tickets (£50 value)',
      '£95 Unlimited question submissions to tutors + tutor phone access',
      'Exam day prep & mental strategies',
      'Full mock exam analysis'
    ],
    features: [
      '20 hours of comprehensive intensive teaching',
      'Maximum contact time with expert tutors',
      'Four conference tickets included (£50 value)',
      '£95 Unlimited question submissions to tutors + tutor phone access',
      'FREE Personalised weekly revision plan (£30 value)',
      'Extended practice with live expert feedback',
      'Complete deep-dive weakness analysis',
      'Advanced drills and practice sessions',
      'Exam day preparation and mental strategies',
      'Full mock exam analysis and feedback',
      'Priority support with 2-hour response times',
      'Maximum preparation - leave nothing to chance'
    ]
  }
];
